apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yogadaily-bot-db-pvc
  labels:
    app: yogadaily-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: "standard" # Раскомментируй и укажи нужный класс хранилища
